<a href="https://colab.research.google.com/github/Praneeth5254/DeepLearning/blob/main/RNN_Sentiment_Analysis_through_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [53]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [54]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [55]:
tokenizer.fit_on_texts(docs)

In [56]:
len(tokenizer.word_index)

17

In [57]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [58]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [60]:
model = Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))# this 18 is the overall vocabulary length which is going to the embedding input, and embedding output shape will be 2, so here for each word ther will be 2 vectors

model.build(input_shape=(None, 5))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)             │ (None, 5, 2)                │              36 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile('adam','accuracy')

In [27]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
[[[ 0.00212288 -0.03965018]
  [ 0.0035874   0.03284184]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]]

 [[ 0.0035874   0.03284184]
  [ 0.0035874   0.03284184]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]]

 [[ 0.039134    0.00578959]
  [ 0.039134    0.00578959]
  [ 0.00917544  0.01683751]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]]

 [[-0.02621902 -0.02551705]
  [-0.03425791  0.00781262]
  [-0.02621902 -0.02551705]
  [ 0.0035874   0.03284184]
  [-0.02621902 -0.02551705]]

 [[ 0.01214436  0.01006617]
  [ 0.04573523  0.00193824]
  [ 0.00346334  0.03644022]
  [ 0.04021065 -0.04077758]
  [-0.02702744  0.01888111]]

 [[ 0.02089206  0.03398779]
  [ 0.02089206  0.03398779]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]
  [-0.02702744  0.01888111]]

 [[ 0.03631289 -0.03026896]
  [ 0.03631289 -0.03026896]
  [-0.02702744  0.01888111]
  [-0.02702744  0.0188811

In [30]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [48]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [49]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [50]:
X_train.shape

(25000, 50)

In [52]:
model = Sequential()
model.add(Embedding(input_dim=88586, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)             │ (None, 50, 2)               │         177,172 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_5 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 178,325 (696.58 KB)

 Trainable params: 178,325 (696.58 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
model = Sequential()
model.add(Embedding(input_dim=88586, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False, input_shape=(50, 2)))  # Specify input shape
model.add(Dense(1, activation='sigmoid'))

model.build(input_shape=(None, 50))  # This explicitly builds the model
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)              │ (None, 50, 2)               │         177,172 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_3 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 178,325 (696.58 KB)

 Trainable params: 178,325 (696.58 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 19ms/step - acc: 0.5036 - loss: 0.6929 - val_acc: 0.5653 - val_loss: 0.6733
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 25ms/step - acc: 0.6664 - loss: 0.6086 - val_acc: 0.7878 - val_loss: 0.4552
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 19ms/step - acc: 0.8717 - loss: 0.3094 - val_acc: 0.7995 - val_loss: 0.4499
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 19ms/step - acc: 0.9307 - loss: 0.1873 - val_acc: 0.7934 - val_loss: 0.5118
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - acc: 0.9576 - loss: 0.1226 - val_acc: 0.7813 - val_loss: 0.5658


In [41]:
print(X_train.shape, X_test.shape)
print(X_train.dtype, X_test.dtype)
print(np.max(X_train), np.min(X_train))  # Ensure max index is within the range of `input_dim`


(25000, 50) (25000, 50)
int32 int32
88585 0


In [40]:
import numpy as np